spring.application.name=Assignment1
server.port=8080

spring.webflux.multipart.max-in-memory-size=25MB
spring.codec.max-in-memory-size=25MB

spring.lifecycle.timeout-per-shutdown-phase=20s

spring.ai.openai.base-url=https://api.openai.com/v1
spring.ai.openai.transcription-model=gpt-4o-mini-transcribe
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=en

server.shutdown=graceful