spring.application.name=Assignment1
server.port=8080

spring.webflux.multipart.max-in-memory-size=25MB
spring.codec.max-in-memory-size=25MB

spring.lifecycle.timeout-per-shutdown-phase=20s

openai.base-url=https://api.openai.com/v1
openai.transcription-model=gpt-4o-mini-transcribe

